// Generated by CoffeeScript 1.7.1
'use strict';
var exec;

exec = require("child_process").exec;

["coffee -b -o ./ -cw src/", "npm start"].forEach(function(command) {
  var child;
  child = exec(command);
  child.unref();
  child.stdout.on("data", function(data) {
    return console.log(data.toString());
  });
  return child.stderr.on("data", function(data) {
    var error;
    error = data.toString();
    if (error === "'coffee' n'est pas reconnu en tant que commande interne") {
      console.log("Reload after install");
      exec("npm install -g coffee-script");
    }
    return console.error(error);
  });
});
