// Generated by CoffeeScript 1.7.1
'use strict';
var app, autoloadDirectories, connect, express, extend, functions, glob, kraken, options, path, port, stitch;

kraken = require('kraken-js');

extend = require('extend');

stitch = require('stitch');

glob = require('glob');

express = require('express');

path = require('path');

connect = require('connect');

app = express();

autoloadDirectories = ['models', 'core/utils'];

options = {
  onconfig: function(config, next) {
    return next(null, config);
  }
};

port = process.env.PORT || 8000;

functions = require('./core/utils/functions');

extend(global, functions);

app.use(kraken(options));

extend(app.locals, functions);

autoloadDirectories.forEach(function(directory) {
  return glob(directory + "/**/*.js", function(er, files) {
    return files.forEach(function(file) {
      var loadedValue, name;
      loadedValue = require('./' + file);
      if (typeof loadedValue.name === 'undefined' || empty(loadedValue.name)) {
        name = file.substr(directory.length + 1).replace(/\.[^\.]+$/g, '');
      } else {
        name = loadedValue.name;
      }
      if (global[name] == null) {
        return global[name] = loadedValue;
      }
    });
  });
});

app.listen(port, function(err) {
  return console.log('[%s] Listening on http://localhost:%d', app.settings.env, port);
});
