// Generated by CoffeeScript 1.7.1
'use strict';
var exec;

exec = require("child_process").exec;

[
    "npm install kraken-js",
    "npm install -g coffee-script",
    "npm install -g nodemon"

].forEach(function(command) {
    var child;
    child = exec(command);
    child.unref();
    child.stdout.on("data", function(data) {
        console.log(data.toString());
    });
    child.stderr.on("data", function(data) {
        var error;
        error = data.toString();
        console.error(error);
    });
});
