// Generated by CoffeeScript 1.7.1
'use strict';
module.exports = function(router) {
  var model;
  model = new IndexModel();
  return router.get('/', function(req, res) {
    return res.render('index', model);
  });
};
