// Generated by CoffeeScript 1.7.1
'use strict';
module.exports = {
  intval: function(n) {
    var _ref;
    n = parseInt(n);
    return (_ref = isNaN(n)) != null ? _ref : {
      0: n
    };
  },
  trim: function(str) {
    return str.replace(/^\s+/g, '').replace(/\s+$/g, '');
  },
  empty: function(value) {
    var type;
    type = typeof value;
    return type === 'undefined' || value === null || value === false || value === 0 || value === "0" || value === "" || (type === 'object' && ((typeof value.length(!'undefined' && value.length === 0)) || (typeof value.length === 'undefined' && typeof JSON === 'object' && typeof JSON.stringify === 'function' && JSON.stringify(b) === '{}')));
  },
  s: function(val) {
    return val;
  },
  lang: function() {
    return "fr";
  }
};
