module.exports = ->
	celibate: s("Célibataire")
	couple: s("En couple")
	fiance: s("Fiancé(e)")
	married: s("Marié(e)")

	men: s("Hommes")
	women: s("Femmes")
	both: s("Hommes et Femmes")

	other: s("Autre")

	firstName: s("Prénom")
	lastName: s("Nom")
	sex: s("Sexe")
	chooseSex: s("Choisissez votre sexe")
	man: s("Homme")
	woman: s("Femme")
	birthDate: s("Date de naissance")
	confidentialityBirthDate: s("Masquer votre date de naissance")
	email: s("Adresse électronique")
	password: s("Mot de passe")
	city: s("Ville actuelle")
	birthCity: s("Ville de naissance")
	job: s("Poste occupé")
	jobPlace: s("Organisation")
	maritalStatus: s("Situation relationnelle")
	loveInterest: s("Intéressé par les")
	biography: s("Biographie")

	noDisplay: s("Ne rien afficher")

	privacy: s("Confidentialité de votre compte")
	private: s("Privé")
	public: s("Public")

	identityTitle: s("Identité")
	identityHint: s("Changez les paramètres de base de votre compte.")
	confidentialityTitle: s("Confidentialité")
	confidentialityHint: s("Changez vos paramètres de confidentialité de votre compte.")
	accountConfidentialityHintPrivate: s("Vos visiteurs ne voient pas les informations que vous avez publiées sauf votre prénom/nom et vos photos de profil. Seuls vos amis peuvent les voir.")
	accountConfidentialityHintPublic: s("Les profils publics s'adressent aux personnalités publiques (sportifs, acteurs, chanteurs, Youtubers, etc.) et seront accessibles partout dans le monde. Les profils privés pourront s'abonner à vous et partager vos publications. Nous tenons à vous rappeler que le passage en public entrainera l'accessibilité de toutes vos anciennes publications.")
	allowFriendPostOnMe: s("Autorisez mes amis à publier des statuts (texte, photos et vidéos) sur mon profil")
	customURL: s("Personnalisation URL")
	btnCheckURLID: s("Vérifier")
	confidentialityFriendList: s("Masquer votre liste d'amis")
	confidentialityFollowList: s("Masquer ma liste d'abonnements")
	certification: s("( Certification )")
	telNumber: s("Numéro de téléphone")
	identityCard: s("Carte d'identité (identity card) : ")
	entrepriseName: s("Nom de l'entreprise")
	kbis: s("Kbis")
	entrepriseRepresentFirstName: s("Prénom du représentant")
	entrepriseRepresentLastName: s("Nom du représentant")
	recepEnreg: s("Récépissé d'enregistrement")
	associationName: s("Nom de l'association")
	userType: s('Vous êtes : ')
	certificationWarning: s('Attention en passant votre compte en privé vous perdrez votre certification.')
