module.exports = ->
	celibate: s("Célibataire")
	couple: s("En couple")
	fiance: s("Fiancé(e)")
	married: s("Marié(e)")

	men: s("Hommes")
	women: s("Femmes")
	both: s("Hommes et Femmes")

	other: s("Autre")

	firstName: s("Prénom")
	lastName: s("Nom")
	sex: s("Sexe")
	chooseSex: s("Choisissez votre sexe")
	man: s("Homme")
	woman: s("Femme")
	birthDate: s("Date de naissance")
	confidentialityBirthDate: s("Masquer votre date de naissance")
	email: s("Adresse électronique")
	password: s("Mot de passe")
	city: s("Ville actuelle")
	birthCity: s("Ville de naissance")
	job: s("Poste occupé")
	jobPlace: s("Organisation")
	maritalStatus: s("Situation relationnelle")
	loveInterest: s("Intéressé par les")
	biography: s("Biographie")

	noDisplay: s("Ne rien afficher")

	privacy: s("Confidentialité de votre compte")
	private: s("Privé")

	identityTitle: s("Identité")
	identityHint: s("Changez les paramètres de base de votre compte.")
	confidentialityTitle: s("Confidentialité")
	confidentialityHint: s("Changez vos paramètres de confidentialité de votre compte.")
	accountConfidentialityHint: s("Vos visiteurs ne voient pas les informations que vous avez publiées sauf votre prénom/nom et vos photos de profil. Seuls vos amis peuvent les voir.")
	confidentialityFriendList: s("Masquer votre liste d'amis")
