// Generated by CoffeeScript 1.7.1
(function() {
  requirejs.config({
    paths: {}
  });

  require(['jquery'], function() {
    var app;
    app = {
      initialize: function() {
        return alert("Loaded");
      }
    };
    return app.initialize();
  });

}).call(this);
